nav:
  Home: /
  About: /about-me/
  Projects: http://github.com/joeprisk

projects_url: http://github.com/joeprisk

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/profile.jpg
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/joeprisk
        twitter: https://twitter.com/joeprisk
        linkedin: https://www.linkedin.com/in/joe-prisk-b9a7252a
        bicycle: https://www.strava.com/athletes/561031
    post_count: 100
    highlight: androidstudio

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-32020580-1 # UA-86660611-1 # enter the tracking ID for your Google Analytics
    go_squared: GSN-965933-T # Go Squared tracking

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
